apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-dpkeys
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
